import { site } from "@/content/site";

import type { LegalContent } from "./types";

const legal = site.legal;

export const legalEn: LegalContent = {
  privacy: {
    eyebrow: "Legal",
    title: "Privacy policy",
    description:
      "How Enriched Studios collects, uses and protects the personal data of anyone visiting the site or requesting a quote.",
    updated: `Last updated: ${legal.updatedEn}`,
    intro:
      "This policy explains what personal data we collect, why we collect it, how long we keep it and what rights you have over it.",
    sections: [
      {
        heading: "1. Who processes your data",
        paragraphs: [
          `The data controller is ${legal.company}, tax number ${legal.vat}, with registered office at ${legal.address}.`,
          `For anything related to personal data, write to ${site.email} or call ${site.phone}.`,
        ],
      },
      {
        heading: "2. What data we collect",
        paragraphs: ["We only collect what we need to reply to you and to keep the site secure."],
        list: [
          "Data you give us in the contact form: name, email, phone (optional), service of interest and the content of your message.",
          "Technical data generated by your visit: IP address and server logs, used only for security and to prevent abuse of the form.",
          "Language preference, stored in your browser so the site opens in the language you chose.",
        ],
      },
      {
        heading: "3. Why we use it and on what legal basis",
        list: [
          "To answer your request and prepare a proposal: pre-contractual steps at your request, Article 6(1)(b) GDPR.",
          "To protect the form from abuse and automated submissions: legitimate interest, Article 6(1)(f) GDPR.",
          "To comply with legal obligations, namely invoicing and tax duties once you become a client: Article 6(1)(c) GDPR.",
        ],
        paragraphs: [
          "We do not use your data for advertising and we do not take automated decisions producing legal effects concerning you.",
        ],
      },
      {
        heading: "4. How long we keep it",
        list: [
          "Enquiries with no commercial follow-up: 12 months from the last communication.",
          "Client data: for the duration of the contract and afterwards for the applicable legal periods, namely 10 years for invoicing records.",
          "Server technical logs: up to 30 days.",
        ],
      },
      {
        heading: "5. Who we share it with",
        paragraphs: [
          "We do not sell or hand over personal data to third parties. We use providers who process data on our behalf, under a data processing agreement:",
        ],
        list: legal.processors.map((processor) => `${processor.name}, for ${processor.roleEn}.`),
      },
      {
        heading: "6. Transfers outside the European Union",
        paragraphs: [
          "Some of these providers may process data outside the European Economic Area. In those cases the transfer relies on standard contractual clauses approved by the European Commission or another mechanism set out in Chapter V of the GDPR.",
        ],
      },
      {
        heading: "7. Your rights",
        paragraphs: ["You can exercise the following rights at any time:"],
        list: [
          "Access your data and obtain a copy.",
          "Correct data that is inaccurate or incomplete.",
          "Ask for erasure when the data is no longer needed.",
          "Ask for restriction of processing, or object to it.",
          "Ask for portability of the data you provided.",
          "Withdraw consent where processing is based on it, without affecting what was done before.",
        ],
      },
      {
        heading: "8. How to exercise them and where to complain",
        paragraphs: [
          `Just write to ${site.email}. We reply within one month, extendable under Article 12 GDPR.`,
          `If you believe the processing breaches the law, you may lodge a complaint with the ${legal.dataProtectionAuthority.name}, the Portuguese supervisory authority.`,
        ],
        links: [{ label: legal.dataProtectionAuthority.name, href: legal.dataProtectionAuthority.url }],
      },
      {
        heading: "9. Security",
        paragraphs: [
          "The site is served over an encrypted connection, the form has submission limits per origin, and access to messages is restricted to the people who need it to reply.",
        ],
      },
      {
        heading: "10. Minors",
        paragraphs: [
          "Our services are aimed at professionals. We do not knowingly collect data from anyone under 16.",
        ],
      },
      {
        heading: "11. Changes to this policy",
        paragraphs: [
          `If anything relevant changes, we update this page and the date at the top. Version in force since ${legal.updatedEn}.`,
        ],
      },
    ],
  },

  terms: {
    eyebrow: "Legal",
    title: "Terms and conditions",
    description:
      "Conditions for using the Enriched Studios website and rules applying to our video production and personal branding services.",
    updated: `Last updated: ${legal.updatedEn}`,
    intro:
      "By using this site you accept the conditions below. They apply to the site and, where relevant, to the services we provide.",
    sections: [
      {
        heading: "1. Service provider",
        paragraphs: [
          `${legal.company}, tax number ${legal.vat}, registered office at ${legal.address}, registered at the ${legal.registry}.`,
          `Contacts: ${site.email}, ${site.phone}. Activity: video production, editing and personal branding for the real estate sector.`,
        ],
      },
      {
        heading: "2. Purpose",
        paragraphs: [
          "This site is informational and commercial: it presents our services and lets you request contact. Browsing it does not create any obligation to contract.",
        ],
      },
      {
        heading: "3. Quotes and orders",
        list: [
          "Prices are not published on the site. Every job is quoted in writing once we understand the scope.",
          "Proposals are valid for 30 days unless stated otherwise.",
          "Amounts are shown in euros and VAT is added at the legal rate where applicable.",
          "Work starts after written acceptance of the proposal and, where agreed, after payment of the deposit.",
        ],
      },
      {
        heading: "4. Deadlines and delivery",
        paragraphs: [
          "The deadlines in each proposal run from the shoot or from receipt of all required materials. Deliverables are provided digitally, through a download link.",
          "The number of included revisions is set out in each proposal. Additional revisions are quoted separately.",
        ],
      },
      {
        heading: "5. Permissions, properties and image rights",
        list: [
          "The client warrants that they have the owner's permission to film and publish the property.",
          "The client warrants that they obtained consent from the people appearing in the footage, under Article 79 of the Portuguese Civil Code.",
          "Unless the client objects in writing, Enriched Studios may use excerpts of the work in its portfolio and social media.",
        ],
      },
      {
        heading: "6. Copyright and licence to use",
        paragraphs: [
          "The pieces we produce are works protected by the Portuguese Copyright Code. On full payment, the client receives a licence to use them for the purposes and channels set out in the proposal.",
          "Raw files and editing projects are not part of the delivery unless agreed in writing.",
        ],
      },
      {
        heading: "7. Website intellectual property",
        paragraphs: [
          "The text, images, brand and code of this site belong to Enriched Studios or to third parties who licensed them to us. They may not be copied or reused without written permission.",
        ],
      },
      {
        heading: "8. Liability",
        paragraphs: [
          "We work to keep the information on the site accurate and current, but we do not guarantee it is free of errors or that the site is available without interruption.",
          "We are not liable for damage arising from the use of third party sites linked from here.",
        ],
      },
      {
        heading: "9. Right of withdrawal",
        paragraphs: [
          "If you are a consumer and the contract is concluded at a distance or off premises, you have 14 days to withdraw without giving a reason, under Portuguese Decree-Law 24/2014.",
          "If you expressly ask for the service to start within that period and it is fully performed, the right of withdrawal ends. If the service has only started, the amount due is proportional to what was performed.",
        ],
      },
      {
        heading: "10. Complaints and dispute resolution",
        paragraphs: [
          "You can submit a complaint through the Portuguese electronic complaints book.",
          `For consumer disputes you may turn to the competent alternative dispute resolution body: ${legal.adr.name}.`,
        ],
        links: [
          { label: "Electronic complaints book", href: legal.complaintsBook },
          { label: legal.adr.name, href: legal.adr.url },
        ],
      },
      {
        heading: "11. Governing law and jurisdiction",
        paragraphs: [
          "Portuguese law applies. The courts of Porto have jurisdiction, without prejudice to mandatory consumer protection rules.",
        ],
      },
      {
        heading: "12. Changes",
        paragraphs: [
          `These conditions may be updated. The applicable version is the one published when you use the site. Version in force since ${legal.updatedEn}.`,
        ],
      },
    ],
  },

  cookies: {
    eyebrow: "Legal",
    title: "Cookie policy",
    description: "Which cookies the Enriched Studios site uses, what they are for and how to control them.",
    updated: `Last updated: ${legal.updatedEn}`,
    intro:
      "Cookies are small files a website stores in your browser. This site uses as few as possible.",
    sections: [
      {
        heading: "1. Cookies we use",
        list: [
          "NEXT_LOCALE: stores the language you chose so the site opens in it next time. Lasts 12 months. It is only created when you use the language switcher, that is, at your request.",
        ],
        paragraphs: [
          "This cookie is strictly necessary to deliver the feature you asked for, so it does not require prior consent under Article 5(3) of Directive 2002/58/EC and Article 5 of Portuguese Law 41/2004.",
        ],
      },
      {
        heading: "2. What we do not use",
        paragraphs: [
          "We do not use analytics, advertising or social media cookies, and we do not share browsing information with third parties for those purposes.",
          "If we ever add analytics or advertising tools, we will ask for your consent before switching them on and update this page.",
        ],
      },
      {
        heading: "3. How to control them",
        paragraphs: [
          "You can delete or block cookies in your browser settings. If you block the language cookie the site still works, it simply stops remembering your choice.",
        ],
      },
      {
        heading: "4. Changes",
        paragraphs: [`Version in force since ${legal.updatedEn}.`],
      },
    ],
  },
};
